### ISSUE TITLE
Change "Pick" with "Ban" when is the ban turn

### ISSUE THREAD

**Issue by Dogemist** [CameronCT/Qrindr#1]
I think is better to see "Ban" when is the ban turn (over the red color) insted of pick

**Comment by CameronCT** [comment]
It is currently like that, but I know there is an issue I believe on Map 4 selection where it has the ban selection listed as a "pick".

**Comment by Dogemist** [comment]
One time do it also during the Map1 Ban where the button was "Pick" instead "Ban"

**Comment by CameronCT** [comment]
Think you can screenshot specifically where you are having this issue? Currently dealing with some flu, but will look into it tomorrow.

**Comment by Dogemist** [comment]
Next time I'll see it I'll post a screenshot, for the moment I use it only for some casual matches

**Comment by CameronCT** [comment]
I have looked into the bug and patched it here: https://github.com/CameronCT/Qrindr/commit/b8f0af37260e7d5d82e5803894c3d494f2b654f7

I will be closing this issue, thank you for reporting it!
