### ISSUE TITLE
The Keen Con Timelimit Duel does not show Copy Pasta correctly

### ISSUE THREAD

**Issue by marcoscv-work** [CameronCT/Qrindr#12]
The copy pasta section does not show Champions, example:

https://qrindr.com/match/86cd9b397fafccbdb2587f97c5fdecae

![image](https://user-images.githubusercontent.com/7963804/151822021-7eb3e6b4-537d-48de-b9ab-368934e209d9.png)

I've been looking for the fix in the file `Qrindr/server/Data/Games/QuakeChampions_TimelimitDuel_KeenCon_BO3.php` but I dinnt see a reason for this issue

**Comment by marcoscv-work** [comment]
Same issue here:
https://github.com/CameronCT/Qrindr/issues/13

**Comment by CameronCT** [comment]
You have to add it to `Match.php`

**Comment by CameronCT** [comment]
It's fixed.

**Comment by marcoscv** [comment]
@CameronCT the players in the copy pasta are those who are banned:

Example:
https://qrindr.com/match/3444da36649dd39fb3123c15b297ac3d
