### ISSUE TITLE
QPL S3S1:BO3 dosen't display correct pasta information

### ISSUE THREAD

**Issue by nyxiadash** [CameronCT/Qrindr#13]
![image](https://user-images.githubusercontent.com/19655371/152093023-f8db5115-264f-4731-8e24-c76e66455662.png)

**Comment by guikolt** [comment]
yeah it's missing the copypasta for s3 here https://github.com/CameronCT/Qrindr/blob/master/server/Match.php#L102

**Comment by CameronCT** [comment]
It's fixed.
