### ISSUE TITLE
Allow to skip cointoss and select winner manually

### ISSUE THREAD

**Issue by rzeka** [CameronCT/Qrindr#2]
Right now we are limited by cointoss when it comes to selecting player that bans first. That's fine in case of "let's just play" situations, but when there's a tournament with proper seeding, rules might force the player that should ban first etc.

The idea is to add another select field, below "best of" with label **Manual cointoss winner** and values:

1. None
1. You
1. Opponent

Tell me if You're interested in PR or would change something. I'll be more than happy to contribute :)

---

Just checked, Quake Challenger rules force that:

> *** Map Ban and Pick Process: ***
> 1. High Seed - High Seed picks first map ban or defer
> 2. Player 1 - Ban Map 1
> 3. Player 2 - Ban Map 2
> 4. Player 1 - Pick Map 1
> 5. Player 2 - Pick Map 2
> 6. Player 1 - Ban Map 3
> 7. Player 2 - Ban Map 4
> 
> *** Champion Ban and Pick Process: ***
> 8. Player 1 - Ban Champion 1 
> 9. Player 2 - Pick Champion Map 1
> 10. Player 1 - Pick Champion Map 1
> 11. Player 2 - Ban Champion 2
> 12. Player 1 - Pick Champion Map 2
> 13. Player 2 - Pick Champion Map 2
> 14. Player 1 - Ban Champion 3
> 15. Player 2 - Pick Champion Map 3
> 16. Player 1 - Pick Champion Map 3

**Comment by CameronCT** [comment]
I have implemented this request, which can be found here: e23a815e10ee...eb923ee05c3a
