### ISSUE TITLE
Champ pick swaped in "Copy Pasta"

### ISSUE THREAD

**Issue by ma1kl** [CameronCT/Qrindr#5]
hi .. i am using qrindr and i saw a bug and i guess this is the right forum to fix it. The first Champ pick is swapped in Copy Pasta. See screenshot.
![image](https://user-images.githubusercontent.com/70756568/92235589-380b2580-eeb4-11ea-84b7-13cf041deda5.png)

**Comment by CameronCT** [comment]
This issue has already been fixed a few hours before this was made. And as of right now the fix is now live on the site.

https://github.com/CameronCT/Qrindr/commit/4e52b96ddf6cca84e8bf93a7e62fc0045d47c9c4
